# Shuffle

In [1]:
import numpy as np

In [2]:
a = np.random.randint(1,20,10)
print(a)

[12  4  7  8  2 17 18 17 18 18]


In [3]:
np.unique(a)

array([ 2,  4,  7,  8, 12, 17, 18])

In [4]:
np.random.shuffle(a)

In [5]:
print(a)

[18  4 18 17  8  2  7 12 18 17]


In [6]:
np.unique(a).size

7